"""Tarif count by doc

Revision ID: d198c7722f11
Revises: 4dd54eb6fda3
Create Date: 2023-07-15 11:19:17.615507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd198c7722f11'
down_revision = '4dd54eb6fda3'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('server_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('acctarifid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'acc_tarifs', ['acctarifid'], ['id'])

    with op.batch_alter_table('tarifs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('countMode', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifs', schema=None) as batch_op:
        batch_op.drop_column('countMode')

    with op.batch_alter_table('server_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('acctarifid')
        batch_op.drop_column('docs')

    # ### end Alembic commands ###
