//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRSoft.NapoleonManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GRSoft.NapoleonManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actgs {
            get {
                object obj = ResourceManager.GetObject("actgs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_xhtml_xml {
            get {
                object obj = ResourceManager.GetObject("application_xhtml_xml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая запись будет удалена, удалить?.
        /// </summary>
        internal static string askToDelRow {
            get {
                return ResourceManager.GetString("askToDelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные были изменены, сохранить?.
        /// </summary>
        internal static string askToSaveChangingData {
            get {
                return ResourceManager.GetString("askToSaveChangingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ca_add {
            get {
                object obj = ResourceManager.GetObject("ca_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dialog_cancel {
            get {
                object obj = ResourceManager.GetObject("dialog_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_sign {
            get {
                object obj = ResourceManager.GetObject("document_sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_clear_4 {
            get {
                object obj = ResourceManager.GetObject("edit_clear_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_find_user {
            get {
                object obj = ResourceManager.GetObject("edit_find_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_user {
            get {
                object obj = ResourceManager.GetObject("edit_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка записи в базу данных.
        /// </summary>
        internal static string errorSaveDb {
            get {
                return ResourceManager.GetString("errorSaveDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap family {
            get {
                object obj = ResourceManager.GetObject("family", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap go_down_4 {
            get {
                object obj = ResourceManager.GetObject("go_down_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap go_up_4 {
            get {
                object obj = ResourceManager.GetObject("go_up_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///   &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=Edge&apos; /&gt;
        ///   &lt;title&gt;User Location&lt;/title&gt;
        ///
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body, html {
        ///         width: 100%;
        ///         height: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///         overflow: hidden;
        ///      }
        ///
        ///      #map {
        ///         height: 100%;
        ///      }
        ///
        ///      .infomsg { display:none; }
        ///   &lt;/style&gt;
        ///
        ///   &lt;script src=&quot;http://maps.googlea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Google_traceroute {
            get {
                return ResourceManager.GetString("Google_traceroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///   &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=Edge&apos; /&gt;
        ///   &lt;title&gt;User Location&lt;/title&gt;
        ///
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body, html {
        ///         width: 100%;
        ///         height: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///         overflow: hidden;
        ///      }
        ///
        ///      #map {
        ///         height: 100%;
        ///      }
        ///
        ///      .infomsg { display:none; }
        ///
        ///   &lt;/style&gt;
        ///
        ///   &lt;script src=&quot;http://maps.googl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Google_userlocation {
            get {
                return ResourceManager.GetString("Google_userlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://grsoft.ru.
        /// </summary>
        internal static string homepage {
            get {
                return ResourceManager.GetString("homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap htmlView {
            get {
                object obj = ResourceManager.GetObject("htmlView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kmenuedit {
            get {
                object obj = ResourceManager.GetObject("kmenuedit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kworldclock {
            get {
                object obj = ResourceManager.GetObject("kworldclock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле логин не может быть пустым.
        /// </summary>
        internal static string loginCantEmpty {
            get {
                return ResourceManager.GetString("loginCantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:info@grsoft.ru.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openstreet;Google;Yandex.
        /// </summary>
        internal static string mapSources {
            get {
                return ResourceManager.GetString("mapSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor_doc {
            get {
                object obj = ResourceManager.GetObject("monitor_doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле имя не может быть пустым.
        /// </summary>
        internal static string nameCantEmpty {
            get {
                return ResourceManager.GetString("nameCantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon napoleon {
            get {
                object obj = ResourceManager.GetObject("napoleon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap object_rotate_left_3 {
            get {
                object obj = ResourceManager.GetObject("object_rotate_left_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap object_rotate_right_3 {
            get {
                object obj = ResourceManager.GetObject("object_rotate_right_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///   &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=Edge&apos; /&gt;
        ///   &lt;title&gt;User Location&lt;/title&gt;
        ///
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body, html {
        ///         width: 100%;
        ///         height: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///         overflow: hidden;
        ///      }
        ///
        ///      #map {
        ///         height: 100%;
        ///      }
        ///
        ///      .infomsg { display:none; }
        ///   &lt;/style&gt;
        ///
        ///   &lt;script src=&quot;http://maps.googlea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Openstreet_traceroute {
            get {
                return ResourceManager.GetString("Openstreet_traceroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///   &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=Edge&apos; /&gt;
        ///   &lt;title&gt;User Location&lt;/title&gt;
        ///
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body, html {
        ///         width: 100%;
        ///         height: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///         overflow: hidden;
        ///      }
        ///
        ///      #map {
        ///         height: 100%;
        ///      }
        ///
        ///      .infomsg { display:none; }
        ///   &lt;/style&gt;
        ///
        ///   &lt;script src=&quot;http://maps.googlea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Openstreet_userlocation {
            get {
                return ResourceManager.GetString("Openstreet_userlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка.
        /// </summary>
        internal static string parking {
            get {
                return ResourceManager.GetString("parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Префикс дублируется!.
        /// </summary>
        internal static string prefixdub {
            get {
                return ResourceManager.GetString("prefixdub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропущен префикс!.
        /// </summary>
        internal static string prefixmissing {
            get {
                return ResourceManager.GetString("prefixmissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле пароль не может быть пустым.
        /// </summary>
        internal static string pwdCantEmpty {
            get {
                return ResourceManager.GetString("pwdCantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_refresh_6 {
            get {
                object obj = ResourceManager.GetObject("view_refresh_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://grsoft.ru/wiki/doku.php.
        /// </summary>
        internal static string wikipagehtml {
            get {
                return ResourceManager.GetString("wikipagehtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///   &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=Edge&apos; /&gt;
        ///   &lt;title&gt;User Location&lt;/title&gt;
        ///
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body, html {
        ///         width: 100%;
        ///         height: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///         overflow: hidden;
        ///      }
        ///
        ///      #map {
        ///         height: 100%;
        ///      }
        ///   &lt;/style&gt;
        ///
        ///   &lt;script src=&quot;http://api-maps.yandex.ru/1.1/index.xml?key=ANzXmEoBAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Yandex_traceroute {
            get {
                return ResourceManager.GetString("Yandex_traceroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///   &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///   &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=Edge&apos; /&gt;
        ///   &lt;title&gt;User Location&lt;/title&gt;
        ///
        ///   &lt;style type=&quot;text/css&quot;&gt;
        ///      body, html {
        ///         width: 100%;
        ///         height: 100%;
        ///         margin: 0;
        ///         padding: 0;
        ///         overflow: hidden;
        ///      }
        ///
        ///      #map {
        ///         height: 100%;
        ///      }
        ///   &lt;/style&gt;
        ///
        ///   &lt;script src=&quot;http://api-maps.yandex.ru/1.1/index.xml?key=ANzXmEoBAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Yandex_userlocation {
            get {
                return ResourceManager.GetString("Yandex_userlocation", resourceCulture);
            }
        }
    }
}
