
/*
 * Copyright (C), 2006-2007, Денис Мосягин
 *
 * Exchange Reflection
 *
 *  ert   01/12/2006   creating
 */ 
#ifndef __REFLECTION_TYPE_H
#define __REFLECTION_TYPE_H

//
//------------------------------- TYPE REFLECTIONS ------------------------------------------
//
BEGIN_TYPE_REFLECTION(Agents)
   REGISTER_STRING_MEMBER(Agents, id)
   REGISTER_STRING_MEMBER(Agents, name)
   REGISTER_STRING_MEMBER(Agents, login)
   REGISTER_STRING_MEMBER(Agents, password)
END_TYPE_REFLECTION(Agents)

BEGIN_TYPE_REFLECTION(Partner)
   REGISTER_STRING_MEMBER(Partner, id)
   REGISTER_STRING_MEMBER(Partner, name)
END_TYPE_REFLECTION(Partner)

BEGIN_TYPE_REFLECTION(Boards)
   REGISTER_STRING_MEMBER(Boards, id)
   REGISTER_STRING_MEMBER(Boards, name)
END_TYPE_REFLECTION(Boards)

BEGIN_TYPE_REFLECTION(Sklad)
   REGISTER_STRING_MEMBER(Sklad, id)
   REGISTER_STRING_MEMBER(Sklad, name)
   REGISTER_STRING_MEMBER(Sklad, unit)
   REGISTER_ULONG_SCALE_MEMBER(Sklad, cost, SUM_SCALE)
   REGISTER_LONG_SCALE_MEMBER(Sklad, qty, QTY_SCALE)
END_TYPE_REFLECTION(Sklad)

BEGIN_TYPE_REFLECTION(WHDocItem)
   REGISTER_STRING_MEMBER(WHDocItem, id)
   REGISTER_STRING_MEMBER(WHDocItem, board)
   REGISTER_LONG_SCALE_MEMBER(WHDocItem, qty, QTY_SCALE)
END_TYPE_REFLECTION(WHDocItem)

BEGIN_TYPE_REFLECTION(WHDoc)
   REGISTER_TIMESTAMP_MEMBER(WHDoc, created)
   REGISTER_STRING_MEMBER(WHDoc, remark)
   REGISTER_STRING_MEMBER(WHDoc, user)
   REGISTER_ULONG_MEMBER(WHDoc, params)
   REGISTER_COLLECTION_MEMBER(WHDoc, items, WHDocItem)
END_TYPE_REFLECTION(WHDoc)

#endif
