serverDefs   = serverDefs.xml
updateFolder = Update
serverBase   = GRServer.sdb
addDefs = addDefs.xml
featuresFile = GRServer.ftr

# параметры для второй службы 
displayName = Сервер "Наполеон 2"
serviceName = GRServer2
