export

include make.vars 

Variant=PavlovaTomsk
#Variant=PavlovaNvkKem
#Variant=PavlovaBrn
#Variant=PavlovaOmsk
#Variant=LeonovaChelyabinsk
#Variant=LeonovaKrasnoyarsk
#Variant=LeonovaTumen
#Variant=LeonovaEburg

include ..\..\make.rull
