#!/usr/bin/sh

# init catalog
#pybabel extract -F babel.cfg -k _l -o messages.pot .
#pybabel init -i messages.pot -d app/translations -l ru

# update catalog
pybabel extract -F babel.cfg -k _l -o messages.pot .
pybabel update -i messages.pot -d app/translations

# compile catalog
# pybabel compile -d app/translations

