"""moy_sklad_log

Revision ID: 060358cfa0f3
Revises: 3b0b6ba0e956
Create Date: 2023-05-09 11:24:22.711319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060358cfa0f3'
down_revision = '3b0b6ba0e956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mskl_acclog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('error', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trace', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mskl_acclog', schema=None) as batch_op:
        batch_op.drop_column('trace')
        batch_op.drop_column('error')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
