//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ads2017.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ads2017.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе (Ctrl+O).
        /// </summary>
        public static string about_hint {
            get {
                return ResourceManager.GetString("about_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точность.
        /// </summary>
        public static string accuracy {
            get {
                return ResourceManager.GetString("accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить пользователя.
        /// </summary>
        public static string add_agent {
            get {
                return ResourceManager.GetString("add_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить запись.
        /// </summary>
        public static string add_description {
            get {
                return ResourceManager.GetString("add_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить подразделение.
        /// </summary>
        public static string add_division {
            get {
                return ResourceManager.GetString("add_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить запись (F8).
        /// </summary>
        public static string add_hint {
            get {
                return ResourceManager.GetString("add_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить руководителя.
        /// </summary>
        public static string add_manager {
            get {
                return ResourceManager.GetString("add_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль настроек МП.
        /// </summary>
        public static string admpwd {
            get {
                return ResourceManager.GetString("admpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агент.
        /// </summary>
        public static string agent {
            get {
                return ResourceManager.GetString("agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агенты в полях.
        /// </summary>
        public static string agents_in_field {
            get {
                return ResourceManager.GetString("agents_in_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть текущее положение пользователей на карте.
        /// </summary>
        public static string agents_in_field_descrition {
            get {
                return ResourceManager.GetString("agents_in_field_descrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агенты в полях (Ctrl+A).
        /// </summary>
        public static string agents_in_field_hint {
            get {
                return ResourceManager.GetString("agents_in_field_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принятая.
        /// </summary>
        public static string apply_task_status {
            get {
                return ResourceManager.GetString("apply_task_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись будет удалена, удалить?.
        /// </summary>
        public static string ask_to_delete {
            get {
                return ResourceManager.GetString("ask_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения?.
        /// </summary>
        public static string ask_to_save {
            get {
                return ResourceManager.GetString("ask_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложения.
        /// </summary>
        public static string attachments {
            get {
                return ResourceManager.GetString("attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите что бы добавить вложения к задаче.
        /// </summary>
        public static string attachments_description {
            get {
                return ResourceManager.GetString("attachments_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавть файл.
        /// </summary>
        public static string attachments_hint {
            get {
                return ResourceManager.GetString("attachments_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Браузер.
        /// </summary>
        public static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть браузер.
        /// </summary>
        public static string browser_description {
            get {
                return ResourceManager.GetString("browser_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть браузер (Ctrl+O).
        /// </summary>
        public static string browser_hint {
            get {
                return ResourceManager.GetString("browser_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте интервал дат.
        /// </summary>
        public static string check_interval {
            get {
                return ResourceManager.GetString("check_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стереть данные.
        /// </summary>
        public static string clear_description {
            get {
                return ResourceManager.GetString("clear_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string clear_hint {
            get {
                return ResourceManager.GetString("clear_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент.
        /// </summary>
        public static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны клиентов.
        /// </summary>
        public static string clients_templates {
            get {
                return ResourceManager.GetString("clients_templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакт.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержание.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать запись.
        /// </summary>
        public static string copy_description {
            get {
                return ResourceManager.GetString("copy_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать (Ctrl+С).
        /// </summary>
        public static string copy_hint {
            get {
                return ResourceManager.GetString("copy_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создана.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построен в системе  &quot;Наполеон&quot;.
        /// </summary>
        public static string created_by_napoleon {
            get {
                return ResourceManager.GetString("created_by_napoleon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать запись.
        /// </summary>
        public static string cut_description {
            get {
                return ResourceManager.GetString("cut_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать (Ctrl+X).
        /// </summary>
        public static string cut_hint {
            get {
                return ResourceManager.GetString("cut_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить пользователя.
        /// </summary>
        public static string del_agent {
            get {
                return ResourceManager.GetString("del_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить запись.
        /// </summary>
        public static string del_description {
            get {
                return ResourceManager.GetString("del_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить подразделение.
        /// </summary>
        public static string del_division {
            get {
                return ResourceManager.GetString("del_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить (Ctrl+D).
        /// </summary>
        public static string del_hint {
            get {
                return ResourceManager.GetString("del_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить руководителя.
        /// </summary>
        public static string del_manager {
            get {
                return ResourceManager.GetString("del_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрет редактирования.
        /// </summary>
        public static string disallow_edit {
            get {
                return ResourceManager.GetString("disallow_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние.
        /// </summary>
        public static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пройденное расстояние:.
        /// </summary>
        public static string distance_gone {
            get {
                return ResourceManager.GetString("distance_gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение.
        /// </summary>
        public static string division {
            get {
                return ResourceManager.GetString("division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнено.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта:.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string excel {
            get {
                return ResourceManager.GetString("excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО.
        /// </summary>
        public static string fio {
            get {
                return ResourceManager.GetString("fio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS - Выключен.
        /// </summary>
        public static string gps_off {
            get {
                return ResourceManager.GetString("gps_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS - Включен.
        /// </summary>
        public static string gps_on {
            get {
                return ResourceManager.GetString("gps_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База знаний !.
        /// </summary>
        public static string help_description {
            get {
                return ResourceManager.GetString("help_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База знаний (F1).
        /// </summary>
        public static string help_hint {
            get {
                return ResourceManager.GetString("help_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        public static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string input_password {
            get {
                return ResourceManager.GetString("input_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал (мин.).
        /// </summary>
        public static string interval_min {
            get {
                return ResourceManager.GetString("interval_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В работе.
        /// </summary>
        public static string inwork {
            get {
                return ResourceManager.GetString("inwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется.
        /// </summary>
        public static string inwork_task_status {
            get {
                return ResourceManager.GetString("inwork_task_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string ip {
            get {
                return ResourceManager.GetString("ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        public static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основное подразделение.
        /// </summary>
        public static string main_division {
            get {
                return ResourceManager.GetString("main_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление подразделениями.
        /// </summary>
        public static string manage_divisions {
            get {
                return ResourceManager.GetString("manage_divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        public static string management {
            get {
                return ResourceManager.GetString("management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование пользователей.
        /// </summary>
        public static string management_description {
            get {
                return ResourceManager.GetString("management_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджмент.
        /// </summary>
        public static string management_hint {
            get {
                return ResourceManager.GetString("management_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руководители.
        /// </summary>
        public static string managers {
            get {
                return ResourceManager.GetString("managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение.
        /// </summary>
        public static string message_description {
            get {
                return ResourceManager.GetString("message_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение для: \{0\}.
        /// </summary>
        public static string message_for {
            get {
                return ResourceManager.GetString("message_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение (F6).
        /// </summary>
        public static string message_hint {
            get {
                return ResourceManager.GetString("message_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История сообщений.
        /// </summary>
        public static string message_history {
            get {
                return ResourceManager.GetString("message_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег.
        /// </summary>
        public static string mileage {
            get {
                return ResourceManager.GetString("mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о пройденном расстоянии.
        /// </summary>
        public static string mileage_description {
            get {
                return ResourceManager.GetString("mileage_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по пробегу (Ctrl+K).
        /// </summary>
        public static string mileage_hint {
            get {
                return ResourceManager.GetString("mileage_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин..
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +7(4852)599-368.
        /// </summary>
        public static string myphone {
            get {
                return ResourceManager.GetString("myphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый агент.
        /// </summary>
        public static string new_agent {
            get {
                return ResourceManager.GetString("new_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое подразделение.
        /// </summary>
        public static string new_division {
            get {
                return ResourceManager.GetString("new_division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый менеджер.
        /// </summary>
        public static string new_manager {
            get {
                return ResourceManager.GetString("new_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непринята.
        /// </summary>
        public static string new_task_status {
            get {
                return ResourceManager.GetString("new_task_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕТ.
        /// </summary>
        public static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕТ,15,30,45,60.
        /// </summary>
        public static string notify_interval {
            get {
                return ResourceManager.GetString("notify_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки.
        /// </summary>
        public static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о заявках пользователей.
        /// </summary>
        public static string orders_description {
            get {
                return ResourceManager.GetString("orders_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки на дополнительные работы.
        /// </summary>
        public static string orders_extended {
            get {
                return ResourceManager.GetString("orders_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки на дополнительные работы (Ctrl+U).
        /// </summary>
        public static string orders_hint {
            get {
                return ResourceManager.GetString("orders_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПК - Выключен.
        /// </summary>
        public static string pda_off {
            get {
                return ResourceManager.GetString("pda_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПК - Включен.
        /// </summary>
        public static string pda_on {
            get {
                return ResourceManager.GetString("pda_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КПК статус.
        /// </summary>
        public static string pda_status {
            get {
                return ResourceManager.GetString("pda_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string performer {
            get {
                return ResourceManager.GetString("performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string performers {
            get {
                return ResourceManager.GetString("performers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотоотчет.
        /// </summary>
        public static string photo_report {
            get {
                return ResourceManager.GetString("photo_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста подождите....
        /// </summary>
        public static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт.
        /// </summary>
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой программы.
        /// </summary>
        public static string pragramm_crashed {
            get {
                return ResourceManager.GetString("pragramm_crashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наполеон - Выход.
        /// </summary>
        public static string programm_finish {
            get {
                return ResourceManager.GetString("programm_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АДС  &quot;&quot;Наполеон&quot;.
        /// </summary>
        public static string programm_name {
            get {
                return ResourceManager.GetString("programm_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наполеон - Запуск.
        /// </summary>
        public static string programm_start {
            get {
                return ResourceManager.GetString("programm_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогресс.
        /// </summary>
        public static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string put {
            get {
                return ResourceManager.GetString("put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить из буфера.
        /// </summary>
        public static string put_descrition {
            get {
                return ResourceManager.GetString("put_descrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить (Ctrl+V).
        /// </summary>
        public static string put_hint {
            get {
                return ResourceManager.GetString("put_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить данные с сервера.
        /// </summary>
        public static string refresh_description {
            get {
                return ResourceManager.GetString("refresh_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить (F5).
        /// </summary>
        public static string refresh_hint {
            get {
                return ResourceManager.GetString("refresh_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отклонена.
        /// </summary>
        public static string reject_task_status {
            get {
                return ResourceManager.GetString("reject_task_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по километражу.
        /// </summary>
        public static string report_by_distance {
            get {
                return ResourceManager.GetString("report_by_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнена.
        /// </summary>
        public static string resolved_task_status {
            get {
                return ResourceManager.GetString("resolved_task_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрут движения.
        /// </summary>
        public static string route {
            get {
                return ResourceManager.GetString("route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть на карте трек пользователя.
        /// </summary>
        public static string route_description {
            get {
                return ResourceManager.GetString("route_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрут движения (Ctrl+R).
        /// </summary>
        public static string route_hint {
            get {
                return ResourceManager.GetString("route_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точки маршрута.
        /// </summary>
        public static string route_points {
            get {
                return ResourceManager.GetString("route_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маршрут.
        /// </summary>
        public static string route2 {
            get {
                return ResourceManager.GetString("route2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения сохранены.
        /// </summary>
        public static string save_complete {
            get {
                return ResourceManager.GetString("save_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить данные.
        /// </summary>
        public static string save_description {
            get {
                return ResourceManager.GetString("save_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка записи в базу данных.
        /// </summary>
        public static string save_error {
            get {
                return ResourceManager.GetString("save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить фото (Ctrl+F5).
        /// </summary>
        public static string save_hint {
            get {
                return ResourceManager.GetString("save_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет сохранение....
        /// </summary>
        public static string saving_process {
            get {
                return ResourceManager.GetString("saving_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искать.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите агентов.
        /// </summary>
        public static string select_agents {
            get {
                return ResourceManager.GetString("select_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите период.
        /// </summary>
        public static string select_period {
            get {
                return ResourceManager.GetString("select_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки подключения.
        /// </summary>
        public static string setting_connect {
            get {
                return ResourceManager.GetString("setting_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки программы (Ctrl+Q).
        /// </summary>
        public static string settings_hint {
            get {
                return ResourceManager.GetString("settings_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string task {
            get {
                return ResourceManager.GetString("task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал задач.
        /// </summary>
        public static string task_journal {
            get {
                return ResourceManager.GetString("task_journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть все задачи.
        /// </summary>
        public static string task_journal_descrition {
            get {
                return ResourceManager.GetString("task_journal_descrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал задач (Ctrl+J).
        /// </summary>
        public static string task_journal_hint {
            get {
                return ResourceManager.GetString("task_journal_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны.
        /// </summary>
        public static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны клиентов.
        /// </summary>
        public static string template_description {
            get {
                return ResourceManager.GetString("template_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны клиентов.
        /// </summary>
        public static string template_hint {
            get {
                return ResourceManager.GetString("template_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время изменено.
        /// </summary>
        public static string time_changed {
            get {
                return ResourceManager.GetString("time_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время факт.
        /// </summary>
        public static string time_fact {
            get {
                return ResourceManager.GetString("time_fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время план.
        /// </summary>
        public static string time_plan {
            get {
                return ResourceManager.GetString("time_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string titlename {
            get {
                return ResourceManager.GetString("titlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выполено.
        /// </summary>
        public static string undone {
            get {
                return ResourceManager.GetString("undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт:.
        /// </summary>
        public static string web_site {
            get {
                return ResourceManager.GetString("web_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы с.
        /// </summary>
        public static string work_time_from {
            get {
                return ResourceManager.GetString("work_time_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать сообщение.
        /// </summary>
        public static string write_message {
            get {
                return ResourceManager.GetString("write_message", resourceCulture);
            }
        }
    }
}
