export default {
  appTitle: "Ace team",

  login: {
    title: "Вход в систему",
    emailLabel: "Введите e-mail",
    passwordLabel: "Введите пароль",
    savePassword: "Сохранить пароль",
    enter: "Войти",
    reqistration: "Регистрация",
    supportEmail: "Написать в тех. поддержку",
    forgotPassword: "Забыли пароль?",
    error: "Пользователь не определен!",
  },
  confirm: {
    title: "Подтверждение email",
  },
  register: {
    title: "Регистрация проекта",
    nameLabel: "Введите имя",
    surnameLabel: "Введите фамилию",
    passwordConfirmLabel: "Повторите пароль",
    registerAction: "Регистрация",
    autorization: "Авторизация",
    projectName: "Название проекта",
    emailAlreadyExists: "E-mail уже был зарегестрирован"
  },
  prjreg: {
    title: "Регистрация проекта",
    countryLabel: "Выберите страну регистрации",
    next: "Продолжить",
    selectCountry: "Выберите страну регистрации",
    currency: "валюта:",
    autoCurrencySelection: "Валюта выбирается автоматически",
    personalAgree: "согласие на обработку персональных данных",
    personal: "персональных данных",
    offerAgree: "согласие с договором",
    offer: "публичной оферты",
  },
  field_is_required: "Заполни поле!",

  countries: {
    AZE: "Азербайджан",
    ARM: "Армения",
    BLR: "Белоруссия",
    BGR: "Болгария",
    GEO: "Грузия",
    ISR: "Израиль",
    IND: "Индия",
    KAZ: "Казахстан",
    KGZ: "Киргизия",
    MDA: "Молдавия",
    MNG: "Монголия",
    ARE: "ОАЭ",
    KOR: "Республика_Корея",
    RUS: "Россия",
    ROU: "Румыния",
    SRB: "Сербия",
    TJK: "Таджикистан",
    TKM: "Туркменистан",
    TUR: "Турция",
    UZB: "Узбекистан",
    UKR: "Украина",
  },
  restore: {
    title: "Забыли пароль?",
    instruction: "Инструкция по восстановлению отправлена на e-mail",
    restore: "Восстановить пароль",
    autorization: "Авторизация",
  },
  menuLabel:{
    profil: "Профиль",
    projects: "Проекты",
    balance: "Баланс",
    tarifs: "Тарифы",
    exit: "Выход",
    organization: "Управление подразделением",
    administration: "Администрирование",
    users:"Управление пользователями",
    structure:"Управление подразделениями",
    command: "Управление коммандой",
    matrix: "Редактор матриц",
    script: "Редактор сценариев",
    manager: "Менеджер",
  },
  profile: {
    title: "Основная информация",
    login: "Логин",
    email: "E-mail",
    phone: "Номер телефона",
    security: "Безопасность",
    position: "Должность",
    password: "Пароль",
    name: "Имя",
    surname: "Фамилия",
    changePassword: "Изменить пароль",
    save: "Сохранить изменения"
  },
  balance: {
    title: "Баланс",
    remnants: "Доступный остаток - ",
    project: "Проект:",
    details: "Детализация",
    table_headers: {
      data: "Дата",
      count_of_users: "Кол-во пользователей",
      project_name: "Название проекта",
      tarif: "Тариф",
      outcoming: "Расход",
      incoming: "Приход",
      sum: "Остаток"
    },
    expense_for_range: "Расход за период: ",
    incoming_for_range: "Приход за период: ",
    code: "Код: ",
    selectDate: "Выберите дату"
  },
  project:{
    title: "Список проектов",
    name: "Проект: ",
    code: "Код проекта: ",
    rename: "Переименовать проект",
    newNamePrompt : 'Введите имя проекта'
  },
  tarif:{
    current: "Текущий тариф",
    currentName: "Название тарифа:",
    cost: "Стоимость тарифа:",
    offer: "Договор публичной офферты:",
    link: "посмотреть",
    details: 'Подробно'
  },
  division:{
    title: "Редактирование подразделений",
    add_department: "Добавить подразделение",
    add_department_prompt: "Введите название подразделения",
    add_manager: "Добавить менеджера",
    add_manager_prompt: "Выберите подразеделение из списка",
    add_manager_prompt2: "Введите имя менеджера",
    edit_manager: "Изменить менеджера",
    delete: "Удалить",
    delete_prompt: "Вы действительно хотите удалить?",
  },
  users:{
    title: "Администрирование пользователей",
    select_division: "Назначить подразделение",
    select_project: "Выбор проекта",
    select_user_type: "Выбр типа пользователя",
    change_connect_status: "Изменить статус подключения",
    table_headers: {
      division: "Подразделение",
      user: "Пользователь",
      version: "Версия ПО",
      access: "Последний доступ",
      status: "Статус подключения",
    },
    edit_division_dlg : {
      title: "Подразделение",
      prompt: "Выберите подразделение из списка",
    },
    user_types : {
      agents: "Агенты",
      managers : "Менеджеры"
    },
    status_connected: "Подключен к серверу",
    status_code: "Код",
    disconnect_uers_promt: "Вы действительно хотите отключить пользователя?"
  },
  dialog: {
    ok: "ОК",
    cancel: "Отмена",
    alert: "Внимание",
  },
  matrix:{
    title: "Редактор матриц",
    add_matrix: "Довавить матрицу",
    edit_matrix: "Переименовать матрицу",
    add_matrix_prompt: "Введите наименование матрицы",
    selected_goods: "Выбранный товар",
    price: "Прайс",
  },
  edit: "Удалить",
  delete: "Изменить",
  matrices: "Матрицы",
  goods: "Товары",
  scripts: "Сценарии",
  documents: "Документы",
  script:{
    title: "Редактор сценариев",
    add_script: "Создать сцнарий",
    add_script_prompt: "Введите наименование сценария",
  },
  documents_label:{
    question: "Анкета",
    incass: "Инкассация",
    remnant: "Остатки",
    visit: "Посещение",
    order: "Заявка",
  }
};
