"""moysklad_rmv_log

Revision ID: 313b6b823c2f
Revises: cb70d1144ae6
Create Date: 2023-07-25 16:02:12.942550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313b6b823c2f'
down_revision = 'cb70d1144ae6'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('mskl_acclog')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mskl_acclog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accid', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.Column('trace', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mskl_acclog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mskl_acclog_accid'), ['accid'], unique=False)
        batch_op.create_index(batch_op.f('ix_mskl_acclog_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mskl_acclog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mskl_acclog_date'))
        batch_op.drop_index(batch_op.f('ix_mskl_acclog_accid'))

    # op.drop_table('mskl_acclog')
    # ### end Alembic commands ###
