apply plugin: 'com.android.application'

android {
    compileSdkVersion 31

    defaultConfig {
        applicationId "com.grsoft.napoleon.dostavka"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 17
        versionName "17"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        market {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions{
        encoding = 'windows-1251'
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        checkReleaseBuilds false
        //abortOnError false
    }

    signingConfigs {
        release {
            keyAlias 'grsoft'
            keyPassword 'GrSoftNapoleon'
            storeFile file(System.getenv('NAPOLEON_KEY'))
            storePassword 'GrSoftNapoleon'
        }

        market {
            keyAlias 'grnpl'
            keyPassword 'GrSoftNapoleon'
            storeFile file(System.getenv('GRNPL_KEY'))
            storePassword 'GrSoftNapoleon'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }

        market {
            signingConfig signingConfigs.market
        }
    }

    applicationVariants.all {
        variant ->
            if (variant.buildType.name == "release")
                variant.outputs.all {
                    outputFileName = "Delivery.apk"
                }
            if (variant.buildType.name == "market")
                variant.outputs.all {
                    outputFileName = "NapoleonMarketDev4.apk"
                }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':delivery')
    implementation project(':lib:camera')

    implementation 'androidx.appcompat:appcompat:1.4.1'
}
