"""MoySklad AccLog change pk

Revision ID: cb70d1144ae6
Revises: d198c7722f11
Create Date: 2023-07-25 11:49:07.328322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb70d1144ae6'
down_revision = 'd198c7722f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mskl_acclog', schema=None) as batch_op:
        batch_op.execute('ALTER TABLE mskl_acclog DROP CONSTRAINT mskl_acclog_pkey CASCADE')

        batch_op.alter_column('accid',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mskl_acclog', schema=None) as batch_op:
        batch_op.execute('ALTER TABLE mskl_acclog DROP CONSTRAINT mskl_acclog_pkey CASCADE')
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('accid',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('id')
        batch_op.create_primary_key('mskl_acclog_pkey', 'mskl_acclog', ['accid','date'])

    # ### end Alembic commands ###
