export

include make.vars 

#Variant=LeonovaIrkUUde
#Variant=LeonovaIrkBlg
#Variant=LeonovaIrkKmsml
Variant=LeonovaIrkHbr
#Variant=LeonovaIrkVld
#Variant=LeonovaIrkNahodka
#Variant=LeonovaYugSah
#Variant=LeonovaNeryungry
#Variant=LeonovaYakutsk
#Variant=LeonovaUssurijsk
#Variant=LeonovaIrkChita
#Variant=LeonovaIrkBratsk

include ..\..\make.rull
