//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Main.rc
//
#define IDS_APP_TITLE                   1
#define IDC_TEST                        2
#define IDCANCEL2                       3
#define COUNT_BTIMAPS_NWS               6
#define COUNT_BTIMAPS_NVS               23
#define COUNT_BTIMAPS                   30
#define IDI_APP                         101
#define IDR_MENU                        102
#define IDS_OK                          103
#define IDS_HELP                        104
#define IDD_ABOUTBOX                    105
#define IDS_ORG_LIST                    107
#define IDD_SHOW                        129
#define IDD_MAIN                        130
#define IDD_ORG_LIST                    131
#define IDD_ORG_DOCS                    132
#define IDB_TOOLBAR                     132
#define IDB_FOLDER                      133
#define IDD_QTY                         134
#define IDD_PRICE_LIST                  135
#define IDD_ORDER_DETAIL                136
#define IDD_REGISTER                    137
#define IDD_ORDER_LIST                  138
#define IDB_CHECKED                     138
#define IDD_SYNC                        139
#define IDD_ORDER_LIST2                 139
#define IDD_DELIVERY                    140
#define IDD_ADMPWD                      141
#define IDD_FLDORGS                     142
#define IDD_HIST                        143
#define IDD_ENTER_COST                  144
#define IDD_INVENT                      145
#define IDD_INVENT_LIST                 146
#define IDD_INVENT_INPUT                147
#define IDD_INVENT_DETAIL               148
#define IDD_REMOVE_ORDERS               149
#define IDD_PRICE_LIST_ADD              150
#define IDR_LIST_FORM                   151
#define IDR_NEW_ORDER                   152
#define IDR_ADD_REMOVE                  153
#define IDD_ORG_REMNANTS                154
#define IDD_REMNANTS_PRICE              155
#define IDD_ORG_DOCS_ADD                156
#define IDD_DLV_PAYS                    157
#define IDD_DELIVERY_ADD                158
#define IDD_ORG_INFO                    159
#define IDD_ORG_INFO_EDIT               160
#define IDD_CONTACT                     161
#define IDD_ORG_POLLS                   162
#define IDD_POLL_FORM                   163
#define IDD_ORG_REMNANTS_BAR            164
#define IDD_POLL_QTY                    165
#define IDD_REPORTS                     166
#define IDD_ORG_LIST_ADD                167
#define IDD_FLDORGS_ADD                 168
#define IDD_PACKETS                     169
#define IDD_ENTER_QTY                   170
#define IDD_INVOICE_ADD                 171
#define IDB_FOLDER32                    172
#define IDB_CHECKED32                   173
#define IDD_DELIVERY_DETAIL             174
#define IDD_BALANCE                     175
#define IDD_QTY_ADD                     176
#define IDC_PRICE_PREFERENCE_ADD        177
#define IDD_SYNC_ADD                    178
#define IDD_REMNANTS                    179
#define IDD_ADDRESS                     180
#define IDD_ACCOUNT                     181
#define IDD_COUNTER                     182
#define IDD_PAY                         183
#define IDB_TOOLBAR32                   184
#define IDB_QTY                         185
#define IDD_VISIT                       186
#define IDD_PROXY                       187
#define IDD_SHEDULE                     188
#define IDD_DETAIL_PAGE2                189
#define IDD_MESSAGE_LIST                190
#define IDD_WAIT_GPS                    191
#define IDD_REMNANTS_QTY                192
#define IDC_UPDATE_DIALOG               193
#define IDD_SCRIPT                      194
#define IDD_SCRIPT_FORM                 195
#define IDD_PAYMENT                     196
#define IDD_PLAN_LIST                   198
#define IDD_SCRIPT_LIST                 199
#define IDC_TEXT                        201
#define IDC_VERSION                     202
#define IDC_COPYRIGHT                   203
#define IDC_ADD                         205
#define IDC_DEL                         206
#define IDC_EDIT                        207
#define IDC_VIEW_TYPE                   208
#define IDC_VIEW_TYPE_CAP               209
#define IDC_PREFERENCE                  210
#define IDC_ORDER_VIEW                  211
#define IDC_DELIVERY_VIEW               212
#define IDC_BALANCE_VIEW                213
#define IDC_BACK                        214
#define IDC_CLOSE                       215
#define IDC_REMOVE_BASE                 216
#define IDC_DETAIL                      217
#define IDC_SEND                        218
#define IDC_ORDER_SUM                   219
#define IDC_PREFERENCE_DIALOG           220
#define IDC_PRICE_PREFERENCE            220
#define IDC_NEXT                        221
#define IDC_PREV                        222
#define IDC_SYNC                        223
#define IDC_REMOVE_EMPTY_ORGS           224
#define IDC_PRICE_FILTER                225
#define IDC_PAY_TIME                    226
#define IDC_UNIT_LIST                   227
#define IDC_DELIVERY_DATE               228
#define IDC_UNIT_TEXT                   229
#define IDC_COST_TEXT                   230
#define IDC_FIND_CODE                   231
#define IDC_PRICE_NUM                   232
#define IDC_BOX_QTY                     233
#define IDC_UNIT_TEXT_LABEL             234
#define IDC_TOP_APP                     235
#define IDC_AUTO_ORDER                  236
#define IDC_GPRS_GATE                   237
#define IDC_GPRS_GATE_LABEL             238
#define IDC_REPORTS                     239
#define IDC_NEW                         240
#define IDC_PRINT_PREFERENCE            241
#define IDC_COPY                        242
#define IDC_SEARCH_ORG                  243
#define IDC_GPS_PREFERENCE_DIALOG       244
#define IDD_PLAN                        245
#define IDD_PLAN_PRICE                  246
#define IDD_STOCK                       247
#define IDD_INCOME                      248
#define IDD_PHOTO_PREFERENCE            249
#define IDC_ONLINE_PREFERENCE           250
#define IDD_VISIT_ADD                   251
#define IDD_DISPLAY                     252
#define IDD_DISPLAY_DETAIL              253
#define IDD_DOC_PAY                     254
#define IDD_RFRG_PAY                    255
#define IDD_REST_OUT                    256
#define IDD_PROXY_ADD                   257
#define IDD_EDIT_PAYMENT                258
#define IDD_UNDLV                       259
#define IDD_FIND                        261
#define IDD_INPUT_BC                    261
#define IDD_PAY_TYPE                    262
#define IDD_ROUTE_LIST                  263
#define IDD_CTRL_DOC_LIST               264
#define IDC_TABLE                       1000
#define IDC_SHOW                        1002
#define IDC_BASE_VERSION                1002
#define IDC_ZAP                         1003
#define IDC_HIST_LIST                   1003
#define IDC_DONE                        1004
#define IDC_REST_LABEL                  1005
#define IDR_MAIN_FRAME                  1006
#define IDC_COST_LABEL                  1006
#define IDC_INPACK_LABEL                1007
#define IDC_REST                        1008
#define IDC_COST                        1009
#define IDC_INPACK                      1010
#define IDC_QTY_LABEL                   1011
#define IDC_SUM_LABEL                   1012
#define IDC_SUM                         1013
#define IDC_QTY                         1014
#define IDC_PACK                        1015
#define IDC_COST_DSC_LABEL              1016
#define IDC_ORDER_DATE                  1017
#define IDC_COST_DSC                    1017
#define IDC_ORDER_TIME                  1018
#define IDC_PLACE_LABEL                 1018
#define IDC_REMARK                      1019
#define IDC_CLEAR_BASE                  1019
#define IDC_PLACE                       1019
#define IDC_PAY_DATE                    1020
#define IDC_ADD_LABEL                   1020
#define IDC_IP                          1021
#define IDC_ADD_QTY                     1021
#define IDC_PORT                        1022
#define IDC_WEIGHT_LABEL                1022
#define IDC_BLW_ZERO                    1023
#define IDC_WEIGHT                      1023
#define IDC_ALERT_BLW                   1024
#define IDC_MIN_LOAD_LABEL              1024
#define IDC_SEL_LAST_ORDER              1025
#define IDC_INPACK2                     1025
#define IDC_LOGIN                       1026
#define IDC_BANK                        1027
#define IDC_SPEC_CND                    1028
#define IDC_TOPIC_B                     1029
#define IDC_PAY_GUARANTY                1029
#define IDC_DISCOUNT                    1030
#define IDC_REMNANTS_ENTER              1030
#define IDC_DISCOUNT_VALUE              1031
#define IDC_RCV_BALANCE                 1032
#define IDC_RCV_PHOTO                   1033
#define IDC_RCV_BALANCE3                1034
#define IDC_SET_FOLDER                  1035
#define IDC_PHOTO                       1036
#define IDC_NET_PREFERENCE_DIALOG       1038
#define IDC_PREV_DATE                   1039
#define IDC_PREV_QTY                    1040
#define IDC_SALES_HIST                  1041
#define IDC_SIP1                        1042
#define IDC_CONFIRM_SEND                1043
#define IDC_DIG_0                       1044
#define IDC_DIG_1                       1045
#define IDC_DIG_2                       1046
#define IDC_DIG_3                       1047
#define IDC_DIG_4                       1048
#define IDC_DIG_5                       1049
#define IDC_DIG_6                       1050
#define IDC_DIG_7                       1051
#define IDC_DIG_8                       1052
#define IDC_DIG_9                       1053
#define IDC_DIG_PT                      1054
#define IDC_DIG_BS                      1055
#define IDC_ORDER_INFO                  1056
#define IDC_ITEM_NAME                   1057
#define IDC_LIST                        1058
#define IDC_ANSWER                      1059
#define IDC_CHECK1                      1059
#define IDC_NET_COST                    1059
#define IDC_AUTO_SAVE                   1059
#define IDC_RESPONSE                    1060
#define IDC_SUPPL                       1061
#define IDC_EDIT1                       1061
#define IDC_COUPON                      1061
#define IDC_CASH                        1061
#define IDC_PASSWORD                    1061
#define IDC_BARCODE                     1061
#define IDC_COST_TYPE                   1062
#define IDC_PWD                         1063
#define IDC_PHOTO_FOLDER                1064
#define IDC_COLUMN2                     1065
#define IDC_COLUMN3                     1066
#define IDC_ITEM_CODE                   1067
#define IDC_FIND                        1068
#define IDC_REMOVE_ORDERS               1069
#define IDC_NEW_SEARCH                  1070
#define IDC_FIND_TEXT                   1071
#define IDO                             1071
#define IDC_REMNANTS_LABEL              1072
#define IDC_SLIDER1                     1072
#define IDC_NEXT_DATE                   1073
#define IDC_DATE_LABEL                  1074
#define IDC_START_DATE                  1075
#define IDC_CALL                        1076
#define IDC_HELD                        1076
#define IDC_ORG_ADDRESS                 1077
#define IDC_TIME_LABEL                  1078
#define IDC_DINNER_LABEL                1079
#define IDC_TIME_START                  1080
#define IDC_ORDER                       1080
#define IDC_TIME_END                    1081
#define IDC_DINNER_START                1082
#define IDC_DINNER_END                  1083
#define IDC_ZREP                        1083
#define IDC_TIME_DASH                   1084
#define IDC_COMBO1                      1084
#define IDC_AGENTS                      1084
#define IDC_DINNER_DASH                 1085
#define IDC_PAY_CHEK                    1085
#define IDC_AGENTS2                     1085
#define IDC_SERVERS                     1085
#define IDC_PHONE                       1086
#define IDC_BUTTON2                     1086
#define IDC_PAY_CARD                    1086
#define IDC_CHANGE                      1086
#define IDC_SAVE                        1086
#define IDC_NAME                        1087
#define IDC_DOC                         1087
#define IDC_LABEL2                      1088
#define IDC_RACK                        1088
#define IDC_LABEL3                      1089
#define IDC_REMOVE                      1089
#define IDC_DATE_BEGIN                  1090
#define IDC_BUTTON1                     1090
#define IDC_DATE_END                    1091
#define IDC_PACKET_INPUT                1092
#define IDC_ORDER_QTY                   1092
#define IDC_MOVE_TO_GROUP               1093
#define IDC_ID                          1093
#define IDC_NEXT32                      1094
#define IDC_BAR                         1094
#define IDC_PREV32                      1095
#define IDC_NAME_LABEL                  1096
#define IDC_ADDRESS_LABEL               1097
#define IDC_INN                         1098
#define IDC_INN_LABEL                   1099
#define IDC_PHONE_LABEL                 1100
#define IDC_PRINT                       1101
#define IDC_DOC_NUMBER                  1102
#define IDC_2_PRICE_ROW                 1103
#define IDD_DELIVERY_LIST               1104
#define IDC_ADD_REMNANTS                1105
#define IDC_DEL_REMNANTS                1106
#define IDC_BANK_LABEL                  1107
#define IDC_2_ORG_ROW                   1108
#define IDC_CHANGE_SORT                 1109
#define IDC_SHOW_2_ROW                  1110
#define IDC_MODEL_LIST                  1111
#define IDC_DEVICE_LIST                 1113
#define IDC_IP2                         1114
#define IDC_PAY                         1115
#define IDC_WALK                        1116
#define IDC_COUNTER                     1117
#define IDC_DIGITS                      1118
#define IDC_TAX                         1119
#define IDC_PHONE1                      1120
#define IDC_SMS                         1121
#define IDC_WAREHOUS                    1122
#define IDC_COST1_LABEL                 1123
#define IDC_COST1                       1124
#define IDC_DELAY                       1125
#define IDC_CACHE                       1126
#define IDC_WAYBILL                     1127
#define IDC_CONTACTS                    1128
#define IDC_CALENDAR                    1129
#define IDC_CONTACTS32                  1130
#define IDC_CALENDAR32                  1131
#define IDC_NET_PREFERENCE_ADD          1132
#define IDC_ORIENTATION                 1133
#define IDC_POWER                       1134
#define IDC_POWER_GOOD                  1135
#define IDC_POWER_HALF                  1136
#define IDC_POWER_LOW                   1137
#define IDC_ENTER_SKU                   1138
#define IDC_MINUS                       1139
#define IDC_SET_VIEW_TYPE               1140
#define IDC_POWER_OFF                   1141
#define IDC_RCV_POD                     1142
#define IDC_INFO                        1143
#define IDC_DOGOVORS                    1144
#define IDC_PROPERTIES                  1145
#define IDC_INFO1                       1146
#define IDC_DOCUMENTS                   1147
#define IDC_REGISTRY                    1148
#define IDC_SERTIFICAT                  1149
#define IDC_OTHER                       1150
#define IDC_CALC                        1151
#define IDC_CALC32                      1152
#define IDC_NOTES                       1153
#define IDC_CAUSE                       1154
#define IDC_PHONE_ONOFF                 1155
#define IDC_COM_PORT                    1156
#define IDC_ORDER_GPS_POS               1157
#define IDC_GPS_TRACK                   1158
#define IDC_GPS_TIME                    1159
#define IDC_DAY_INTERVAL                1160
#define IDC_GSM_CELL                    1161
#define IDC_ROUTE                       1162
#define IDC_NONE                        1163
#define IDC_WARNING                     1164
#define IDC_TASK                        1165
#define IDC_REMARK2                     1166
#define IDC_AGENT                       1167
#define IDC_KEYVALUE                    1168
#define IDC_DISCOUNT_LABEL              1169
#define IDC_UNIT_LABEL                  1170
#define IDC_WAREHOUSE                   1171
#define IDC_ACCURACY                    1172
#define IDC_REST_LABEL2                 1173
#define IDC_REST2                       1174
#define IDC_UPDATE                      1175
#define IDC_SORT_NO_CASE                1176
#define IDC_FIRMS                       1177
#define IDD_ENTER_VALUE                 1178
#define IDC_MIN_LOAD                    1179
#define IDC_COEF                        1180
#define IDC_PLAN_ITEM                   1181
#define IDC_USER                        1182
#define IDC_DOC_LIST                    1183
#define IDC_ORG_PLAN                    1184
#define IDC_ORG_PLANS                   1185
#define IDC_REPLACE_ADD_DEL             1186
#define IDC_REPLACE                     1187
#define IDC_ORDER_ONLINE                1188
#define IDC_DRIVER                      1189
#define IDC_NC_TASK                     1190
#define IDC_AGENT_TASK                  1191
#define IDC_IP1_ONLINE                  1192
#define IDC_IP2_ONLINE                  1193
#define IDC_NEW_DAY                     1194
#define IDC_CONTACT_EDIT                1195
#define IDD_INCASS                      1196
#define IDC_MESSAGE                     1197
#define IDD_RETURN                      1198
#define IDD_BONUS                       1199
#define IDC_GSM_TRACK                   1200
#define IDD_GOODS_REST                  1201
#define IDD_GOODS_PRICE                 1202
#define IDD_GOODS_ITEMS                 1203
#define IDD_PPAY                        1204
#define IDC_HEIGHT                      1205
#define IDC_WIDTH                       1206
#define IDC_PACKET                      1207
#define IDC_MATRIX                      1208
#define IDC_MULTIWH                     1209
#define IDC_FLAT_PRICE                  1210
#define IDC_MULT_QTY                    1211
#define IDC_MULT_QTY_LABEL              1212
#define IDC_ALL                         1213
#define IDC_RED_FILTER                  1214
#define IDC_YLW_FILTER                  1215
#define IDC_FAIL                        1217
#define IDC_FIND_CLEAR                  1218
#define IDB_ORDER_STATUS                1219
#define IDS_NETWORK                     10000
#define IDS_MAIN_SETTINGS               10001
#define IDS_SETTINGS                    10002
#define IDS_ERROR_IN_SYNC               10003
#define IDS_SYNC_ENDED                  10004
#define IDS_MESSAGE                     10005
#define IDS_CANT_OPEN_DB                10006
#define IDS_ERROR                       10007
#define IDS_ERROR_CODE                  10008
#define IDS_PROCESS_SETTINGS            10009
#define IDS_PROCESSING                  10010
#define IDS_ERROR_PROCESSING            10011
#define IDS_SERVER_NOT_RESPONSE         10012
#define IDS_TX_DATA                     10013
#define IDS_RX_DATA                     10014
#define IDS_PROCESS_DATA                10015
#define IDS_DATA_SENDED                 10016
#define IDS_ERROR_WHILE_RCV             10017
#define IDS_PRICE                       10018
#define IDS_PRICE_FOLDERS               10019
#define IDS_WARNING                     10020
#define IDS_CLEAR_BASE_ALERT            10021
#define IDS_PROCESS_ORDER               10022
#define IDS_NAME                        10023
#define IDS_QTY                         10024
#define IDS_SUM                         10025
#define IDS_COST                        10026
#define IDS_ADDRESS                     10027
#define IDS_ADDRESS_LABEL               10027
#define IDS_STRING10028                 10028
#define IDS_DATE                        10028
#define IDS_CLIENT                      10029
#define IDS_PHONE                       10030
#define IDS_STRING10031                 10031
#define IDS_PAY                         10031
#define IDS_UNDLV_WARN                  10032
#define IDS_QUESTION                    10033
#define IDS_SET_UNDLV_CAUSE_ALERT       10034
#define IDS_CASH                        10035
#define IDS_CASH_CHEK                   10036
#define IDS_INFO                        10037
#define IDS_PREPARE                     10038
#define IDS_ERROR_IN_TX                 10039
#define IDS_ERROR_PRINT_CHEK            10040
#define IDS_DISCOUNT                    10041
#define IDS_TIME                        10042
#define IDS_TIME_LABEL                  10042
#define IDS_NUM                         10043
#define IDS_QTY_TOTAL                   10044
#define IDS_CARD_PROCESS_ERROR          10045
#define IDS_ORDER_HELDED                10046
#define IDS_NOT_OPEN                    10047
#define IDS_WORK_DAY_NOT_OPEN           10048
#define IDS_QTY_ABOVE                   10049
#define IDC_INPUT_BARCODE               10050
#define IDS_AGENTS                      10050
#define IDC_F1                          10050
#define IDS_DOC_TYPES                   10051
#define IDS_CTRL_DOCS                   10052
#define IDS_CTRL_QTY                    10053
#define IDS_STRING10054                 10054
#define IDS_QTY_HEAD                    10054
#define IDS_DOC                         10055
#define IDC_QUIT                        32772
#define IDC_F4                          32775
#define IDC_LANGUAGE_ID                 39217
#define IDM_OK                          40000
#define IDM_HELP                        40001
#define IDC_ABOUT                       40002
#define IDC_RCV_PRICE                   40003
#define IDC_REGISTER                    40004
#define IDR_ADD_REMOVE_COPY             40006
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
