apply plugin: 'com.android.application'

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "com.grsoft.napoleon"
        minSdkVersion 15
        targetSdkVersion 29
        versionCode 16
        versionName "16"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        market {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions.encoding = 'windows-1251'

    lintOptions {
        checkReleaseBuilds false
        //abortOnError false
    }

    signingConfigs {
        release {
            keyAlias 'grsoft'
            keyPassword 'GrSoftNapoleon'
            storeFile file(System.getenv('NAPOLEON_KEY'))
            storePassword 'GrSoftNapoleon'
        }

        market {
            keyAlias 'grnpl'
            keyPassword 'GrSoftNapoleon'
            storeFile file(System.getenv('GRNPL_KEY'))
            storePassword 'GrSoftNapoleon'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }

        market {
            signingConfig signingConfigs.market
        }
    }

    flavorDimensions "version"
    productFlavors{
        apk1{
            dimension "version"
            applicationId "com.grsoft.napoleon"
        }

        apk2{
            dimension "version"
            applicationId "com.grsoft.napoleon2"
        }

        apk3{
            dimension "version"
            applicationId "com.grsoft.napoleon3"
        }
    }


    applicationVariants.all {
        variant ->
            if (variant.buildType.name == "release"&& variant.productFlavors[0].name.equals("apk1"))
                variant.outputs.all {
                    outputFileName = "Pavlov.apk"
                }
            if (variant.buildType.name == "release"&& variant.productFlavors[0].name.equals("apk2"))
                variant.outputs.all {
                    outputFileName = "Pavlov2.apk"
                }
            if (variant.buildType.name == "release"&& variant.productFlavors[0].name.equals("apk3"))
                variant.outputs.all {
                    outputFileName = "Pavlov3.apk"
                }
            if (variant.buildType.name == "market")
                variant.outputs.all {
                    outputFileName = "NapoleonMarketDev4.apk"
                }
    }


}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':tradebase')

    implementation 'androidx.appcompat:appcompat:1.0.0'

}
