
/*
 * Copyright (C), 2006-2007, Денис Мосягин
 *
 * Exchange Reflection
 *
 *  ert   01/12/2006   creating
 */ 
#ifndef __REFLECTION_TYPE_H
#define __REFLECTION_TYPE_H

//
//------------------------------- TYPE REFLECTIONS ------------------------------------------
//
BEGIN_TYPE_REFLECTION(Price)
   REGISTER_STRING_MEMBER(Price, id)
   REGISTER_STRING_MEMBER(Price, name)
   REGISTER_STRING_MEMBER(Price, packName)
   REGISTER_STRING_MEMBER(Price, barcode)
   REGISTER_STRING_MEMBER(Price, boxBarcode)
   REGISTER_ULONG_SCALE_MEMBER2(Price, qtyInPack, QTY_SCALE, true)
END_TYPE_REFLECTION(Price)

BEGIN_TYPE_REFLECTION(WHDocItem)
   REGISTER_STRING_MEMBER(WHDocItem, id)
   REGISTER_USHORT_MEMBER(WHDocItem, isBaseUnit)
   REGISTER_LONG_SCALE_MEMBER2(WHDocItem, packCoef, QTY_SCALE, true)
   REGISTER_LONG_SCALE_MEMBER2(WHDocItem, qty, QTY_SCALE, true)
END_TYPE_REFLECTION(WHDocItem)

BEGIN_TYPE_REFLECTION(WHDocs)
   REGISTER_FILETIME_MEMBER(WHDocs, date)
   REGISTER_STRING_MEMBER(WHDocs, id)
   REGISTER_STRING_MEMBER(WHDocs, name)
   REGISTER_STRING_MEMBER(WHDocs, number)
   REGISTER_STRING_MEMBER(WHDocs, type)

   REGISTER_COLLECTION_MEMBER(WHDocs, items, WHDocItem)
END_TYPE_REFLECTION(WHDocs)

BEGIN_TYPE_REFLECTION(ReqDocParam)
   REGISTER_FILETIME_MEMBER(ReqDocParam, date)
   REGISTER_STRING_MEMBER(ReqDocParam, id)
   REGISTER_STRING_MEMBER(ReqDocParam, type)
   REGISTER_STRING_MEMBER(ReqDocParam, number)
	REGISTER_USHORT_MEMBER(ReqDocParam, status)
END_TYPE_REFLECTION(ReqDocParam)

BEGIN_TYPE_REFLECTION(ReqDocAnswer)
   REGISTER_STRING_MEMBER(ReqDocAnswer, message)
	REGISTER_USHORT_MEMBER(ReqDocAnswer, status)
END_TYPE_REFLECTION(ReqDocAnswer)

BEGIN_TYPE_REFLECTION(WhOutDocItem)
   REGISTER_STRING_MEMBER(WhOutDocItem, id)
   REGISTER_USHORT_MEMBER(WhOutDocItem, isBaseUnit)
   REGISTER_LONG_SCALE_MEMBER2(WhOutDocItem, packCoef, QTY_SCALE, true)
   REGISTER_LONG_SCALE_MEMBER2(WhOutDocItem, qty, QTY_SCALE, true)
   REGISTER_LONG_SCALE_MEMBER2(WhOutDocItem, inputQty, QTY_SCALE, true)
END_TYPE_REFLECTION(WhOutDocItem)

BEGIN_TYPE_REFLECTION(WhOutDoc)
   REGISTER_FILETIME_MEMBER(WhOutDoc, date)
   REGISTER_TIMESTAMP_MEMBER(WhOutDoc, created)
   REGISTER_STRING_MEMBER(WhOutDoc, id)
   REGISTER_STRING_MEMBER(WhOutDoc, number)
   REGISTER_STRING_MEMBER(WhOutDoc, name)
   REGISTER_STRING_MEMBER(WhOutDoc, type)
	REGISTER_USHORT_MEMBER(WhOutDoc, flags)

   REGISTER_COLLECTION_MEMBER(WhOutDoc, items, WhOutDocItem)
END_TYPE_REFLECTION(WhOutDoc)
#endif
