export

include make.vars 

#Variant = Pavlov
#Variant = PavlovStore
Variant = PavlovKonovalova
#Variant=Smirnova
#Variant = SmirnovaSharia


include ..\..\make.rull

#install: logcab 1cplugin

#logistic:  dbpda libpda
#	$(MAKE) -f logistic.mk pch
#	$(MAKE) -f logistic.mk

#logcab: logistic
#	$(MAKE) -f logistic.mk cab
