serverDefs   = serverDefs.xml
updateFolder = Update
serverBase   = GRServer.sdb
# addDefs = dispatch.xml
addDefs = addDefs.xml
featuresFile = GRServer.ftr

#imageFolder = .\
#
# включить работу с дбф в ansi-кодировке
#dbfCodePage = ansi
#
# параметры для второй службы 
#displayName = Сервер "Наполеон 2"
#serviceName = GRServer2
#
#ограничение на размер одной сессии 200 мб (по умолчанию 50)
#SessionMemoryLimit = 200
#
#ограничение на размер выдуленной памяти 2000 мб (по умолчанию 1000)
#MemoryLimit=2000
#