"""bog_payments

Revision ID: a349ba64a119
Revises: f9c305eb5078
Create Date: 2023-06-07 23:23:33.104573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a349ba64a119'
down_revision = 'f9c305eb5078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bog_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=300), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bog_status')
    # ### end Alembic commands ###
