include ':app'

include ':managerbase'
project(':managerbase').projectDir = new File('..\\..\\modules\\managerbase\\')

include ':itext'
project(':itext').projectDir = new File('..\\..\\modules\\itext\\')

include ':network'
project(':network').projectDir = new File('..\\..\\modules\\network\\')

include ':json'
project(':json').projectDir = new File('..\\..\\modules\\json\\')

include ':tradebase'
project(':tradebase').projectDir = new File('..\\..\\modules\\tradebase\\')

include ':mpchart'
project(':mpchart').projectDir = new File('..\\..\\modules\\mpchart\\')

rootProject.name = "Sweet Market Manager"