"""payze_payments

Revision ID: 16b98dee2007
Revises: a349ba64a119
Create Date: 2023-06-12 13:12:29.076328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b98dee2007'
down_revision = 'a349ba64a119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payze_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.Column('payment_id', sa.String(length=300), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payze_status')
    # ### end Alembic commands ###
