"""moy_sklad

Revision ID: 3b0b6ba0e956
Revises: c8bae89cf56c
Create Date: 2023-04-23 17:12:54.094498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0b6ba0e956'
down_revision = 'c8bae89cf56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mskl_acclog',
    sa.Column('accid', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('accid', 'date')
    )
    with op.batch_alter_table('mskl_acclog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mskl_acclog_accid'), ['accid'], unique=False)
        batch_op.create_index(batch_op.f('ix_mskl_acclog_date'), ['date'], unique=False)

    op.create_table('mskl_account',
    sa.Column('accid', sa.String(length=100), nullable=False),
    sa.Column('srv_token', sa.String(length=100), nullable=True),
    sa.Column('json_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('accid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mskl_account')
    with op.batch_alter_table('mskl_acclog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mskl_acclog_date'))
        batch_op.drop_index(batch_op.f('ix_mskl_acclog_accid'))

    op.drop_table('mskl_acclog')
    # ### end Alembic commands ###
