"""payments_table

Revision ID: 4dd54eb6fda3
Revises: e968f8e3fcb6
Create Date: 2023-06-12 18:22:01.653119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd54eb6fda3'
down_revision = 'e968f8e3fcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_pay_id'), ['pay_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_pay_id'))
        batch_op.drop_column('pay_id')

    # ### end Alembic commands ###
