"""ReqConnect

Revision ID: c8bae89cf56c
Revises: 125d6412ceba
Create Date: 2023-02-02 18:26:00.774287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bae89cf56c'
down_revision = '125d6412ceba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('req_connect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=120), nullable=True),
    sa.Column('server_code', sa.String(length=120), nullable=True),
    sa.Column('user_type', sa.String(length=120), nullable=True),
    sa.Column('valid_till', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('req_connect')
    # ### end Alembic commands ###
