"""balance

Revision ID: f9c305eb5078
Revises: 060358cfa0f3
Create Date: 2023-05-12 04:37:53.934516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c305eb5078'
down_revision = '060358cfa0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('finish', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serverid', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('agents', sa.Integer(), nullable=True),
    sa.Column('expense', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('server_stats', schema=None) as batch_op:
        batch_op.create_index('serv_stat_idx', ['date', 'serverid'], unique=False)

    op.create_table('tarifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonusid', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sum', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bonusid'], ['bonus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarif_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarifid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tarifid'], ['tarifs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acc_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('sum', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sumbank', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('remark', sa.String(length=1000), nullable=True),
    sa.Column('bonusid', sa.Integer(), nullable=True),
    sa.Column('payerid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acc_payments', schema=None) as batch_op:
        batch_op.create_index('acc_payment_idx', ['date', 'accountid'], unique=False)

    op.create_table('acc_tarifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=True),
    sa.Column('serverid', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('tarifid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tarifid'], ['tarifs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acc_tarifs', schema=None) as batch_op:
        batch_op.create_index('acc_tarif_idx', ['date', 'serverid'], unique=False)
        batch_op.create_index(batch_op.f('ix_acc_tarifs_accountid'), ['accountid'], unique=False)

    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('sum', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.create_index('balance_idx', ['date', 'accountid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_index('balance_idx')

    op.drop_table('balance')
    with op.batch_alter_table('acc_tarifs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acc_tarifs_accountid'))
        batch_op.drop_index('acc_tarif_idx')

    op.drop_table('acc_tarifs')
    with op.batch_alter_table('acc_payments', schema=None) as batch_op:
        batch_op.drop_index('acc_payment_idx')

    op.drop_table('acc_payments')
    op.drop_table('tarif_details')
    op.drop_table('bonus_details')
    op.drop_table('accounts')
    op.drop_table('tarifs')
    with op.batch_alter_table('server_stats', schema=None) as batch_op:
        batch_op.drop_index('serv_stat_idx')

    op.drop_table('server_stats')
    op.drop_table('bonus')
    # ### end Alembic commands ###
