/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSymbol.c                                          *
* Font:        Arial Narrow                                          *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\STM32\NGB_CST_FILES\xxx.txt                  *
* Range enabled:        0030 - 0039                                  *
* Edit/Insert/Right     at character 0x30 (48)                       *
* Edit/Insert/Right     at character 0x30 (48)                       *
* Edit/Insert/Right     at character 0x30 (48)                       *
* Edit/Insert/Left      at character 0x30 (48)                       *
* Edit/Insert/Left      at character 0x30 (48)                       *
* Edit/Insert/Left      at character 0x30 (48)                       *
*                                                                    *
**********************************************************************
*                                                                    *
* Edit/Insert/Right     at character 0x30 (48)                       *
* Edit/Insert/Right     at character 0x30 (48)                       *
* Pixel index of character 0x30 (48) at 14/1 set to 1                *
* Pixel index of character 0x30 (48) at 15/2 set to 1                *
* Pixel index of character 0x30 (48) at 15/3 set to 1                *
* Pixel index of character 0x30 (48) at 15/4 set to 1                *
* Pixel index of character 0x30 (48) at 15/5 set to 1                *
* Pixel index of character 0x30 (48) at 15/6 set to 1                *
* Pixel index of character 0x30 (48) at 15/7 set to 1                *
* Pixel index of character 0x30 (48) at 15/8 set to 1                *
* Pixel index of character 0x30 (48) at 15/9 set to 1                *
* Pixel index of character 0x30 (48) at 15/10 set to 1               *
* Pixel index of character 0x30 (48) at 15/11 set to 1               *
* Pixel index of character 0x30 (48) at 15/11 set to 0               *
* Pixel index of character 0x30 (48) at 14/12 set to 1               *
* Pixel index of character 0x30 (48) at 15/11 set to 1               *
*                                                                    *
**********************************************************************
  C-file modified by emWin Font Converter (ST) version 5.26: Feb 08 2017 at 10:06:05
  C-file modified by emWin Font Converter (ST) version 5.26: Feb 08 2017 at 10:09:16
*                                                                    *
* Pixel index of character 0x33 (51) at 3/8 set to 1                 *
* Pixel index of character 0x33 (51) at 4/9 set to 1                 *
* Pixel index of character 0x33 (51) at 5/10 set to 1                *
* Pixel index of character 0x33 (51) at 6/10 set to 1                *
* Pixel index of character 0x33 (51) at 7/10 set to 1                *
* Pixel index of character 0x33 (51) at 8/10 set to 1                *
* Pixel index of character 0x33 (51) at 9/10 set to 1                *
* Pixel index of character 0x33 (51) at 10/10 set to 1               *
* Pixel index of character 0x33 (51) at 11/9 set to 1                *
* Pixel index of character 0x33 (51) at 12/8 set to 1                *
* Pixel index of character 0x33 (51) at 4/4 set to 1                 *
* Pixel index of character 0x33 (51) at 4/5 set to 1                 *
* Pixel index of character 0x33 (51) at 5/5 set to 1                 *
* Pixel index of character 0x33 (51) at 5/4 set to 1                 *
* Pixel index of character 0x33 (51) at 11/4 set to 1                *
* Pixel index of character 0x33 (51) at 12/4 set to 1                *
* Pixel index of character 0x33 (51) at 12/4 set to 0                *
* Pixel index of character 0x33 (51) at 10/4 set to 1                *
* Pixel index of character 0x33 (51) at 10/5 set to 1                *
* Pixel index of character 0x33 (51) at 11/5 set to 1                *
* Pixel index of character 0x33 (51) at 7/7 set to 1                 *
* Pixel index of character 0x33 (51) at 8/7 set to 1                 *
*                                                                    *
**********************************************************************
  C-file modified by emWin Font Converter (ST) version 5.26: Feb 08 2017 at 11:09:08
*                                                                    *
* Character enabled:   0x3F (63)                                     *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Edit/Insert/Right     at character 0x3F (63)                       *
* Pixel index of character 0x3F (63) at 0/0 set to 1                 *
* Pixel index of character 0x3F (63) at 0/0 set to 0                 *
* Pixel index of character 0x3F (63) at 0/21 set to 0                *
* Pixel index of character 0x3F (63) at 0/21 set to 1                *
* Pixel index of character 0x3F (63) at 0/21 set to 0                *
* Pixel index of character 0x3F (63) at 0/21 set to 1                *
* Pixel index of character 0x3F (63) at 0/21 set to 0                *
* Pixel index of character 0x3F (63) at 0/21 set to 1                *
* Pixel index of character 0x3F (63) at 0/21 set to 0                *
* Pixel index of character 0x3F (63) at 0/21 set to 1                *
* Pixel index of character 0x3F (63) at 0/21 set to 0                *
* Pixel index of character 0x3F (63) at 0/21 set to 1                *
* Pixel index of character 0x3F (63) at 0/21 set to 0                *
* Pixel index of character 0x3F (63) at 0/21 set to 1                *
* Pixel index of character 0x3F (63) at 0/21 set to 0                *
* Pixel index of character 0x3F (63) at 0/21 set to 1                *
* Pixel index of character 0x3F (63) at 0/21 set to 0                *
*                                                                    *
**********************************************************************
  C-file modified by emWin Font Converter (ST) version 5.26: Feb 15 2017 at 15:10:13
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSymbol;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0030[ 28] = { /* code 0030, DIGIT ZERO */
  __XXXXXX,XXXXXX__,
  _X______,______X_,
  X_______,_______X,
  X_______,_______X,
  X_______,_______X,
  X_______,_______X,
  X_______,_______X,
  X_______,_______X,
  X_______,_______X,
  X_______,_______X,
  X_______,_______X,
  X_______,_______X,
  _X______,______X_,
  __XXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0031[ 28] = { /* code 0031, DIGIT ONE */
  __XXXXXX,XXXXXX__,
  _XXXXXXX,______X_,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  XXXXXXXX,_______X,
  _XXXXXXX,______X_,
  __XXXXXX,XXXXXX__};


GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0032[ 28] = { /* code 0030, DIGIT THREE */
  __XXXXXX,XXXXXX__,
  _X______,______X_,
  X_____XX,XX_____X,
  X___XX__,__XX___X,
  X__XX___,___XX__X,
  X__X___X,____X__X,
  X__X___X,X___X__X,
  X__X___X,XX_XX__X,
  X__X___X,XXXX___X,
  X______X,XXXX___X,
  X______X,XXXXX__X,
  X_______,_______X,
  _X______,______X_,
  __XXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0033[ 28] = { /* code 0032, DIGIT TWO */
  __XXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXX__};
  
GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0034[ 28] = { /* code 0033, DIGIT Four */
  __XXXXXX,XXXXXX__,
  _X______,______X_,
  X_______,_______X,
  X_______,_______X,
  X___XX__,__XX___X,
  X___XX__,__XX___X,
  X_______,_______X,
  X______X,X______X,
  X__X____,____X__X,
  X___X___,___X___X,
  X____XXX,XXX____X,
  X_______,_______X,
  _X______,______X_,
  __XXXXXX,XXXXXX__};


GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0035[ 14] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,
  _X______,
  _X______,
  _X______,
  X_______,
  X_XXXX__,
  XX____X_,
  X______X,
  _______X,
  _______X,
  X______X,
  X_____XX,
  _X___XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0036[ 14] = { /* code 0036, DIGIT SIX */
  ___XXX__,
  _XX___X_,
  _X_____X,
  X______X,
  X_______,
  X_XXXX__,
  XX____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  _X_____X,
  _XX___X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0037[ 14] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,
  _______X,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __XX____,
  __X_____,
  __X_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0038[ 14] = { /* code 0038, DIGIT EIGHT */
  __XXXX__,
  _X____X_,
  X______X,
  X______X,
  X______X,
  XX____XX,
  _XXXXXX_,
  XX____XX,
  X______X,
  X______X,
  X______X,
  X______X,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_0039[ 14] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _XX___X_,
  XX____X_,
  X______X,
  X______X,
  X______X,
  X______X,
  _X____XX,
  __XXXX_X,
  _______X,
  X______X,
  X_____X_,
  _X___XX_,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSymbol_003F[ 14] = { /* code 003F, QUESTION MARK */
  __XXXX__,
  _XX__XX_,
  XX____XX,
  X______X,
  _______X,
  _____XX_,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ___XX___,
  ___XX___,
  ________};


GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFontSymbol_CharInfo[11] = {
   {  16,  14,   0,   5,  16, acGUI_FontFontSymbol_0030 } /* code 0030, DIGIT ZERO */
  ,{  16,  14,   0,   5,  16, acGUI_FontFontSymbol_0031 } /* code 0031, DIGIT ONE */
  ,{  16,  14,   0,   5,  16, acGUI_FontFontSymbol_0032 } /* code 0032, DIGIT TWO */
  ,{  16,  14,   0,   5,  16, acGUI_FontFontSymbol_0033 } /* code 0033, DIGIT THREE */
  ,{  16,  14,   0,   5,  16, acGUI_FontFontSymbol_0034 } /* code 0034, DIGIT FOUR */
  ,{   8,  14,   0,   5,   9, acGUI_FontFontSymbol_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  14,   0,   5,   9, acGUI_FontFontSymbol_0036 } /* code 0036, DIGIT SIX */
  ,{   8,  14,   0,   5,   9, acGUI_FontFontSymbol_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  14,   0,   5,   9, acGUI_FontFontSymbol_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  14,   0,   5,   9, acGUI_FontFontSymbol_0039 } /* code 0039, DIGIT NINE */
  ,{   8,  14,   0,   5,   9, acGUI_FontFontSymbol_003F } /* code 003F, QUESTION MARK */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSymbol_Prop2 = {
   0x003F /* first character */
  ,0x003F /* last character  */
  ,&GUI_FontFontSymbol_CharInfo[ 10] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFontSymbol_Prop1 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontFontSymbol_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSymbol_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSymbol = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSymbol_Prop1}
  ,19 /* Baseline */
  ,0 /* Height of lowercase characters */
  ,0 /* Height of capital characters */
};

