export

Variant=ClearLineBaltic
#Variant=ClearLine
#Variant=Aproyan
#Variant=Charhifalakyan
#Variant=Chotulidi
#Variant=Kirakosyan
#Variant=Muradyan
#Variant=Nikulin
#Variant=Torosyan

include make.vars 

include ..\..\make.rull
