export

#Variant = Lisan
#Variant = Leopard
#Variant = Alcobisness
#Variant = Zenit
#Variant = Victoria
#Variant = Rusalka
Variant = LVVK

ifeq ($(Variant),)
$(error "Set variant before")
endif

include make.vars 

include ..\..\make.rull
