serverDefs = C:\Works\Napoleon\Core\GRServer\Server\Core\objects\serverDefs.xml
addDefs = ..\Changes\addDefs.xml
serverBase = GRServer.sdb
updateFolder = Update\
exchangeFolder = Exp
pluginsFolder = .\
Port = 8888
featuresFile = GRServer.ftr
#dbfCodePage = ansi
Debug=full