apply plugin: 'com.android.application'

android {
    compileSdkVersion 31

    defaultConfig {
        applicationId "com.grsoft.napoleon"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 23
        versionName "23"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        market {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions.encoding = 'windows-1251'

    lintOptions {
        checkReleaseBuilds false
        //abortOnError false
    }

    signingConfigs {
        release {
            keyAlias 'grsoft'
            keyPassword 'GrSoftNapoleon'
            storeFile file(System.getenv('NAPOLEON_KEY'))
            storePassword 'GrSoftNapoleon'
        }

        market {
            keyAlias 'grnpl'
            keyPassword 'GrSoftNapoleon'
            storeFile file(System.getenv('GRNPL_KEY'))
            storePassword 'GrSoftNapoleon'
        }
    }

    buildTypes {
        debug {
            manifestPlaceholders.access_background_location = "android.permission.ACCESS_BACKGROUND_LOCATION"
        }

        release {
            signingConfig signingConfigs.release
            manifestPlaceholders.access_background_location = "android.permission.ACCESS_BACKGROUND_LOCATION"
        }

        market {
            signingConfig signingConfigs.market
            manifestPlaceholders.access_background_location = "fake.name"
        }
    }

    applicationVariants.all {
        variant ->
            if (variant.buildType.name == "release")
                variant.outputs.all {
                    outputFileName = "SunFruitBerry.apk"
                }
            if (variant.buildType.name == "market")
                variant.outputs.all {
                    outputFileName = "NapoleonMarketDev4.apk"
                }
    }
}

dependencies {
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    def fragment_version = "1.4.1"
    def lifecycle_version = "2.5.0-alpha05"

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':base')

    implementation 'androidx.appcompat:appcompat:1.1.0'

    implementation "androidx.fragment:fragment:$fragment_version"

    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata:$lifecycle_version"
    // Lifecycles only (without ViewModel or LiveData)
    implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"

    // Saved state module for ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"

    // alternately - if using Java8, use the following instead of lifecycle-compiler
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.1.0'
}
