
/*
 * Copyright (C), 2006-2007, Денис Мосягин
 *
 * Exchange Reflection
 *
 *  ert   01/12/2006   creating
 */ 
#ifndef __REFLECTION_TYPE_H
#define __REFLECTION_TYPE_H

//
//------------------------------- TYPE REFLECTIONS ------------------------------------------
//
BEGIN_TYPE_REFLECTION(Price)
   REGISTER_STRING_MEMBER(Price, id)
   REGISTER_STRING_MEMBER(Price, name)
   REGISTER_STRING_MEMBER(Price, barcode)
   REGISTER_STRING_MEMBER(Price, bcPack)
   REGISTER_ULONG_SCALE_MEMBER2(Price, inPack, QTY_SCALE, true)
END_TYPE_REFLECTION(Price)

BEGIN_TYPE_REFLECTION(WhSklad)
   REGISTER_STRING_MEMBER(WhSklad, id)
   REGISTER_STRING_MEMBER(WhSklad, name)
END_TYPE_REFLECTION(WhSklad)

BEGIN_TYPE_REFLECTION(WhSkaldRest)
   REGISTER_STRING_MEMBER(WhSkaldRest, id)
   REGISTER_STRING_MEMBER(WhSkaldRest, name)
   REGISTER_STRING_MEMBER(WhSkaldRest, barcode)
   REGISTER_STRING_MEMBER(WhSkaldRest, bcPack)
   REGISTER_STRING_MEMBER(WhSkaldRest, idWh)
   REGISTER_STRING_MEMBER(WhSkaldRest, idRack)
   REGISTER_ULONG_SCALE_MEMBER2(WhSkaldRest, qty, QTY_SCALE, true)
   REGISTER_ULONG_SCALE_MEMBER2(WhSkaldRest, inPack, QTY_SCALE, true)
	REGISTER_FILETIME_MEMBER(WhSkaldRest, bottling)
END_TYPE_REFLECTION(WhSkaldRest)

BEGIN_TYPE_REFLECTION(SkMarks)
   REGISTER_STRING_MEMBER(SkMarks, id)
   REGISTER_STRING_MEMBER(SkMarks, markBegin)
   REGISTER_STRING_MEMBER(SkMarks, markEnd)
END_TYPE_REFLECTION(SkMarks)

BEGIN_TYPE_REFLECTION(PartCode)
   REGISTER_STRING_MEMBER(PartCode, id)
   REGISTER_STRING_MEMBER(PartCode, code)
END_TYPE_REFLECTION(PartCode)

BEGIN_TYPE_REFLECTION(DocTypes)
   REGISTER_STRING_MEMBER(DocTypes, id)
   REGISTER_STRING_MEMBER(DocTypes, name)
   REGISTER_LONG_MEMBER(DocTypes, controlDoc)
   REGISTER_LONG_MEMBER(DocTypes, controlRack)
   REGISTER_LONG_MEMBER(DocTypes, controlItem)
   REGISTER_LONG_MEMBER(DocTypes, controlQty)
   REGISTER_LONG_MEMBER(DocTypes, isRouteList)
   REGISTER_LONG_MEMBER(DocTypes, isMovement)
   REGISTER_LONG_MEMBER(DocTypes, isDKA1)
   REGISTER_LONG_MEMBER(DocTypes, isDKA2)
   REGISTER_LONG_MEMBER(DocTypes, isScanDoc)
END_TYPE_REFLECTION(DocTypes)

BEGIN_TYPE_REFLECTION(WhAgents)
   REGISTER_STRING_MEMBER(WhAgents, id)
   REGISTER_STRING_MEMBER(WhAgents, userid)
   REGISTER_USHORT_MEMBER(WhAgents, canInputQty)
   REGISTER_USHORT_MEMBER(WhAgents, canInputInPack)
   REGISTER_USHORT_MEMBER(WhAgents, canMixInput)
   REGISTER_USHORT_MEMBER(WhAgents, inputRack)
END_TYPE_REFLECTION(WhAgents)

BEGIN_TYPE_REFLECTION(Config)
   REGISTER_STRING_MEMBER(Config, key)
   REGISTER_STRING_MEMBER(Config, value)
END_TYPE_REFLECTION(Config)

BEGIN_TYPE_REFLECTION(OrderItem)
   REGISTER_STRING_MEMBER(OrderItem, id)
   REGISTER_STRING_MEMBER(OrderItem, rack)
   REGISTER_STRING_MEMBER(OrderItem, rackDest)
   REGISTER_STRING_MEMBER(OrderItem, mark)
   REGISTER_STRING_MEMBER(OrderItem, barcode)
   REGISTER_STRING_MEMBER(OrderItem, palletBarcode)
   REGISTER_LONG_SCALE_MEMBER2(OrderItem, qty, QTY_SCALE, true)
   REGISTER_USHORT_MEMBER(OrderItem, flags)
END_TYPE_REFLECTION(OrderItem)

BEGIN_TYPE_REFLECTION(WhOrder)
   REGISTER_TIMESTAMP_MEMBER(WhOrder, created)
   REGISTER_STRING_MEMBER(WhOrder, id)
   REGISTER_ULONG_MEMBER(WhOrder, params)

   REGISTER_COLLECTION_MEMBER(WhOrder, items, OrderItem)
END_TYPE_REFLECTION(WhOrder)

BEGIN_TYPE_REFLECTION(DKA1Doc)
   REGISTER_TIMESTAMP_MEMBER(DKA1Doc, created)
   REGISTER_STRING_MEMBER(DKA1Doc, id)
   REGISTER_ULONG_MEMBER(DKA1Doc, params)
   REGISTER_STRING_MEMBER(DKA1Doc, packBC)
   REGISTER_COLLECTION_MEMBER(DKA1Doc, items, OrderItem)
END_TYPE_REFLECTION(DKA1Doc)

BEGIN_TYPE_REFLECTION(DKA2Doc)
   REGISTER_TIMESTAMP_MEMBER(DKA2Doc, created)
   REGISTER_STRING_MEMBER(DKA2Doc, id)
   REGISTER_STRING_MEMBER(DKA2Doc, packBC)
   REGISTER_ULONG_MEMBER(DKA2Doc, params)
   REGISTER_COLLECTION_MEMBER(DKA2Doc, items, OrderItem)
END_TYPE_REFLECTION(DKA2Doc)

BEGIN_TYPE_REFLECTION(ScanDocItem)
   REGISTER_STRING_MEMBER(ScanDocItem, barCode)
END_TYPE_REFLECTION(ScanDocItem)

BEGIN_TYPE_REFLECTION(ScanDoc)
   REGISTER_TIMESTAMP_MEMBER(ScanDoc, created)
   REGISTER_STRING_MEMBER(ScanDoc, id)
   REGISTER_ULONG_MEMBER(ScanDoc, params)
   REGISTER_COLLECTION_MEMBER(ScanDoc, items, ScanDocItem)
END_TYPE_REFLECTION(ScanDoc)

BEGIN_TYPE_REFLECTION(ControlDoc)
   REGISTER_STRING_MEMBER(ControlDoc, id)

   REGISTER_COLLECTION_MEMBER(ControlDoc, items, OrderItem)
END_TYPE_REFLECTION(ControlDoc)

BEGIN_TYPE_REFLECTION(OrderProceeded)
   REGISTER_FILETIME_MEMBER(OrderProceeded, created)
   REGISTER_STRING_MEMBER(OrderProceeded, remark)
   REGISTER_STRING_MEMBER(OrderProceeded, type)
END_TYPE_REFLECTION(OrderProceeded)

BEGIN_TYPE_REFLECTION(PalletItem)
   REGISTER_STRING_MEMBER(PalletItem, id)
   REGISTER_STRING_MEMBER(PalletItem, barcode)
	REGISTER_ULONG_SCALE_MEMBER(PalletItem, qty, QTY_SCALE)
END_TYPE_REFLECTION(PalletItem)

BEGIN_TYPE_REFLECTION(Pallets)
   REGISTER_STRING_MEMBER(Pallets, barcode)
   REGISTER_COLLECTION_MEMBER(Pallets, items, PalletItem)
END_TYPE_REFLECTION(Pallets)

BEGIN_TYPE_REFLECTION(ItemGroups)
   REGISTER_STRING_MEMBER(ItemGroups, barcode)
   REGISTER_COLLECTION_MEMBER(ItemGroups, items, PalletItem)
END_TYPE_REFLECTION(ItemGroups)

#endif
