serverDefs = D:\Works\Napoleon.ce\Core.New\GRServer\Server\Core\objects\serverDefs.xml
serverBase = GRServer.sdb
updateFolder = Update\
exchangeFolder = .\Exp\
pluginsFolder = .\
Port = 8888
featuresFile = GRServer.ftr
imageFolder = .\
jsLogin = test
jsPassword = test
Debug = full
#addDefs = addDefs.xml
