//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3643
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRSoft.Ads.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GRSoft.Ads.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap appointment_new {
            get {
                object obj = ResourceManager.GetObject("appointment_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_double_3 {
            get {
                object obj = ResourceManager.GetObject("arrow-down-double-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;info&quot; (&quot;key&quot; TEXT PRIMARY KEY, &quot;value&quot;);
        ///INSERT INTO &quot;info&quot; VALUES (&quot;version&quot;, &quot;1&quot;);
        ///CREATE TABLE &quot;Kladr&quot; (&quot;code&quot;  TEXT  ,&quot;name&quot;  TEXT  ,&quot;socr&quot;  TEXT  , CONSTRAINT pk_Kladr PRIMARY KEY (&quot;code&quot;));
        ///CREATE TABLE &quot;Street&quot; (&quot;code&quot;  TEXT  ,&quot;name&quot;  TEXT  ,&quot;socr&quot;  TEXT  , CONSTRAINT pk_Street PRIMARY KEY (&quot;code&quot;));.
        /// </summary>
        internal static string CreateLocalDatabase {
            get {
                return ResourceManager.GetString("CreateLocalDatabase", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_clear_4 {
            get {
                object obj = ResourceManager.GetObject("edit-clear-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap go_down_search {
            get {
                object obj = ResourceManager.GetObject("go_down_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap go_up_search {
            get {
                object obj = ResourceManager.GetObject("go_up_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !name Google;
        ///-----------------------------------------------------------------------------------------------
        ///!beginmap orgaddress
        ///&lt;!DOCTYPE html &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot;
        ///&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///&lt;title&gt;Google Maps JavaScript API Example&lt;/title&gt;
        ///&lt;script src=&quot;http://maps.google.com/maps?file=api&amp;amp;v=2&amp;amp;key=AIzaSyAeWKxqpiIfDLaYF7uowGWL5Rker [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Google_maps {
            get {
                return ResourceManager.GetString("Google_maps", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap monitor_doc {
            get {
                object obj = ResourceManager.GetObject("monitor_doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !name Openstreet;
        ///
        ///-----------------------------------------------------------------------------------------------
        ///!beginmap orgaddress
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;OpenStreetMap&lt;/title&gt;
        ///  &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        /// 
        ///  &lt;script src=&quot;http://maps.google.com/maps?file=api&amp;amp;v=2&amp;amp;key=AIzaSyAeWKxqpiIfDLaYF7uowGWL5Rker [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Openstreet_maps {
            get {
                return ResourceManager.GetString("Openstreet_maps", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !name Yandex;
        ///-----------------------------------------------------------------------------------------------
        ///!beginmap orgaddress
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt; 
        ///&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt; 
        ///&lt;script src=&quot;http://api-maps.yandex.ru/1.1/index.xml?key=ANzXmEoBAAAAkjQFPwIAQphddQGLBfkqE3qCI3Vo8OCM8yYAAAAAAAAAAACYpxbA0OaEdJRuAHC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Yandex_maps {
            get {
                return ResourceManager.GetString("Yandex_maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !name Народные карты Yandex;
        ///-----------------------------------------------------------------------------------------------
        ///!beginmap orgaddress
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt; 
        ///&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt; 
        ///&lt;script src=&quot;http://api-maps.yandex.ru/1.1/index.xml?key=ANzXmEoBAAAAkjQFPwIAQphddQGLBfkqE3qCI3Vo8OCM8yYAAAAAAAAAAACYpxb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Народные_карты_Yandex_maps {
            get {
                return ResourceManager.GetString("Народные_карты_Yandex_maps", resourceCulture);
            }
        }
    }
}
